# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JGKit-Plus.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JGKitPlusMainWindows(object):
    def setupUi(self, JGKitPlusMainWindows):
        JGKitPlusMainWindows.setObjectName("JGKitPlusMainWindows")
        JGKitPlusMainWindows.resize(800, 600)
        JGKitPlusMainWindows.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(JGKitPlusMainWindows)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 558))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.TreeAndMemoryLayout = QtWidgets.QVBoxLayout()
        self.TreeAndMemoryLayout.setSpacing(0)
        self.TreeAndMemoryLayout.setObjectName("TreeAndMemoryLayout")
        self.TreeLayout = QtWidgets.QHBoxLayout()
        self.TreeLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.TreeLayout.setObjectName("TreeLayout")
        self.DeviceDisplayTree = QtWidgets.QTreeView(self.centralwidget)
        self.DeviceDisplayTree.setObjectName("DeviceDisplayTree")
        self.TreeLayout.addWidget(self.DeviceDisplayTree)
        self.DeviceEditTree = QtWidgets.QTreeView(self.centralwidget)
        self.DeviceEditTree.setObjectName("DeviceEditTree")
        self.TreeLayout.addWidget(self.DeviceEditTree)
        self.TreeLayout.setStretch(0, 1)
        self.TreeLayout.setStretch(1, 1)
        self.TreeAndMemoryLayout.addLayout(self.TreeLayout)
        self.MemoryLayout = QtWidgets.QHBoxLayout()
        self.MemoryLayout.setSpacing(0)
        self.MemoryLayout.setObjectName("MemoryLayout")
        self.MemoryView = QtWidgets.QListView(self.centralwidget)
        self.MemoryView.setObjectName("MemoryView")
        self.MemoryLayout.addWidget(self.MemoryView)
        self.MemoryTable = QtWidgets.QTableView(self.centralwidget)
        self.MemoryTable.setObjectName("MemoryTable")
        self.MemoryLayout.addWidget(self.MemoryTable)
        self.MemoryLayout.setStretch(0, 1)
        self.MemoryLayout.setStretch(1, 3)
        self.TreeAndMemoryLayout.addLayout(self.MemoryLayout)
        self.TreeAndMemoryLayout.setStretch(0, 2)
        self.TreeAndMemoryLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.TreeAndMemoryLayout, 0, 0, 1, 1)
        JGKitPlusMainWindows.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JGKitPlusMainWindows)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        JGKitPlusMainWindows.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JGKitPlusMainWindows)
        self.statusbar.setObjectName("statusbar")
        JGKitPlusMainWindows.setStatusBar(self.statusbar)
        self.actionSave_Configure = QtWidgets.QAction(JGKitPlusMainWindows)
        self.actionSave_Configure.setObjectName("actionSave_Configure")
        self.actionSave_Configure_As = QtWidgets.QAction(JGKitPlusMainWindows)
        self.actionSave_Configure_As.setObjectName("actionSave_Configure_As")
        self.actionImport_Configure = QtWidgets.QAction(JGKitPlusMainWindows)
        self.actionImport_Configure.setObjectName("actionImport_Configure")
        self.menuFile.addAction(self.actionSave_Configure)
        self.menuFile.addAction(self.actionSave_Configure_As)
        self.menuFile.addAction(self.actionImport_Configure)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(JGKitPlusMainWindows)
        QtCore.QMetaObject.connectSlotsByName(JGKitPlusMainWindows)

    def retranslateUi(self, JGKitPlusMainWindows):
        _translate = QtCore.QCoreApplication.translate
        JGKitPlusMainWindows.setWindowTitle(_translate("JGKitPlusMainWindows", "JGKit-Plus"))
        self.menuFile.setTitle(_translate("JGKitPlusMainWindows", "File"))
        self.actionSave_Configure.setText(_translate("JGKitPlusMainWindows", "Save Configure"))
        self.actionSave_Configure_As.setText(_translate("JGKitPlusMainWindows", "Save Configure As"))
        self.actionImport_Configure.setText(_translate("JGKitPlusMainWindows", "Import Configure"))
